<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW53JxFd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW53JxFd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW53JxFd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW53JxFd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW53JxFd\App_KernelDevDebugContainer([
    'container.build_hash' => 'W53JxFd',
    'container.build_id' => '0f3bdcc6',
    'container.build_time' => 1644947610,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW53JxFd');
